### ISSUE TITLE
it worked for 1 day but Suddenly stucked in UI 

### ISSUE THREAD

**Issue by allaf2** [chrisleekr/binance-trading-bot#102]
[2021-04-17T10:33:45.411Z] ERROR: binance-api/37 on 384644bb0fb9: Execution failed. (version=0.0.65, server=cronjob, job=trailingTrade, uuid=9a3424e5-3b5a-4128-b35b-c6f5347e3b98, symbol=DENTUSDT, err.code=-1021)
    Error: Timestamp for this request is outside of the recvWindow.
        at /srv/node_modules/binance-api-node/dist/http-client.js:93:17
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async execute (/srv/app/jobs/trailingTrade/step/get-account-info.js:23:23)
        at async execute (/srv/app/jobs/trailingTrade.js:98:14)
        at async CronJob.<anonymous> (/srv/app/server-cronjob.js:29:11)

**Comment by allaf2** [comment]
my problem has been fixed by:
sudo yum install ntp

on centos7

**Comment by chrisleekr** [comment]
Hi @allaf2 

Good to hear that you fixed the issue. Please close the issue.

**Comment by ryuheechul** [comment]
in ubuntu's (on wsl2) case, this worked, https://github.com/microsoft/WSL/issues/4149#issuecomment-521877012
