### ISSUE TITLE
Doesn't load

### ISSUE THREAD

**Issue by kaziqta** [chrisleekr/binance-trading-bot#11]
It just keeps on hanging and spinning when opening at http://localhost:8080

```
(node:38) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token u in JSON at position 0

at JSON.parse (<anonymous>)

at handleLatest (/srv/app/websocket/handlers/latest.js:33:23)

at runMicrotasks (<anonymous>)

at processTicksAndRejections (internal/process/task_queues.js:93:5)

at async WebSocket.<anonymous> (/srv/app/websocket/configure.js:43:11)

(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 52)

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"msg":"Trade: Simple Stop-Chasing","time":"2021-02-17T18:59:51.001Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"simpleStopChaserConfig":{"enabled":true,"cronTime":"* * * * * *","symbols":["BTCUPUSDT","ETHUPUSDT","BNBUPUSDT","XRPUPUSDT","ADADOWNUSDT","LTCDOWNUSDT","TRXUPUSDT","LINKUPUSDT","BCHUPUSDT"],"candles":{"interval":"15m","limit":200},"maxPurchaseAmount":100,"stopLossLimit":{"lastBuyPercentage":1.06,"stopPercentage":0.97,"limitPercentage":0.969}},"msg":"Successfully retrieved configuration from the cache.","time":"2021-02-17T18:59:51.002Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"symbols":["BTCUPUSDT","ETHUPUSDT","BNBUPUSDT","XRPUPUSDT","ADADOWNUSDT","LTCDOWNUSDT","TRXUPUSDT","LINKUPUSDT","BCHUPUSDT"],"msg":"Checking symbols...","time":"2021-02-17T18:59:51.002Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"cachedLastSymbol":"BNBUPUSDT","msg":"Cached last symbol","time":"2021-02-17T18:59:51.003Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"cachedSymbolIndex":2,"msg":"Found symbol index","time":"2021-02-17T18:59:51.003Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","level":30,"currentSymbol":"XRPUPUSDT","msg":"Determined current symbol","time":"2021-02-17T18:59:51.003Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","symbol":"XRPUPUSDT","symbolUuid":"feb85fab-4612-422f-9513-0ba6dbc5214b","level":30,"msg":"Start processing symbol...","time":"2021-02-17T18:59:51.004Z","v":0}

{"name":"binance-api","version":"0.0.52","hostname":"addd366f6812","pid":38,"server":"cronjob","job":"simpleStopChaser","uuid":"3c219a02-94d4-4824-82c2-edd561b88896","symbol":"XRPUPUSDT","symbolUuid":"feb85fab-4612-422f-9513-0ba6dbc5214b","level":30,"cachedExchangeInfo":"[\"BTCUSDT\",\"ETHUSDT\",\"BNBUSDT\",\"BCCUSDT\",\"NEOUSDT\",\"LTCUSDT\",\"QTUMUSDT\",\"ADAUSDT\",\"XRPUSDT\",\"EOSUSDT\",\"TUSDUSDT\",\"IOTAUSDT\",\"XLMUSDT\",\"ONTUSDT\",\"TRXUSDT\",\"ETCUSDT\",\"ICXUSDT\",\"VENUSDT\",\"NULSUSDT\",\"VETUSDT\",\"PAXUSDT\",\"BCHABCUSDT\",\"BCHSVUSDT\",\"USDCUSDT\",\"LINKUSDT\",\"WAVESUSDT\",\"BTTUSDT\",\"USDSUSDT\",\"ONGUSDT\",\"HOTUSDT\",\"ZILUSDT\",\"ZRXUSDT\",\"FETUSDT\",\"BATUSDT\",\"XMRUSDT\",\"ZECUSDT\",\"IOSTUSDT\",\"CELRUSDT\",\"DASHUSDT\",\"NANOUSDT\",\"OMGUSDT\",\"THETAUSDT\",\"ENJUSDT\",\"MITHUSDT\",\"MATICUSDT\",\"ATOMUSDT\",\"TFUELUSDT\",\"ONEUSDT\",\"FTMUSDT\",\"ALGOUSDT\",\"USDSBUSDT\",\"GTOUSDT\",\"ERDUSDT\",\"DOGEUSDT\",\"DUSKUSDT\",\"ANKRUSDT\",\"WINUSDT\",\"COSUSDT\",\"NPXSUSDT\",\"COCOSUSDT\",\"MTLUSDT\",\"TOMOUSDT\",\"PERLUSDT\",\"DENTUSDT\",\"MFTUSDT\",\"KEYUSDT\",\"STORMUSDT\",\"DOCKUSDT\",\"WANUSDT\",\"FUNUSDT\",\"CVCUSDT\",\"CHZUSDT\",\"BANDUSDT\",\"BUSDUSDT\",\"BEAMUSDT\",\"XTZUSDT\",\"RENUSDT\",\"RVNUSDT\",\"HCUSDT\",\"HBARUSDT\",\"NKNUSDT\",\"STXUSDT\",\"KAVAUSDT\",\"ARPAUSDT\",\"IOTXUSDT\",\"RLCUSDT\",\"MCOUSDT\",\"CTXCUSDT\",\"BCHUSDT\",\"TROYUSDT\",\"VITEUSDT\",\"FTTUSDT\",\"BUSDTRY\",\"USDTTRY\",\"USDTRUB\",\"EURUSDT\",\"OGNUSDT\",\"DREPUSDT\",\"BULLUSDT\",\"BEARUSDT\",\"ETHBULLUSDT\",\"ETHBEARUSDT\",\"TCTUSDT\",\"WRXUSDT\",\"BTSUSDT\",\"LSKUSDT\",\"BNTUSDT\",\"LTOUSDT\",\"EOSBULLUSDT\",\"EOSBEARUSDT\",\"XRPBULLUSDT\",\"XRPBEARUSDT\",\"STRATUSDT\",\"AIONUSDT\",\"MBLUSDT\",\"COTIUSDT\",\"BNBBULLUSDT\",\"BNBBEARUSDT\",\"STPTUSDT\",\"USDTZAR\",\"WTCUSDT\",\"DATAUSDT\",\"XZCUSDT\",\"SOLUSDT\",\"USDTIDRT\",\"CTSIUSDT\",\"HIVEUSDT\",\"CHRUSDT\",\"BTCUPUSDT\",\"BTCDOWNUSDT\",\"GXSUSDT\",\"ARDRUSDT\",\"LENDUSDT\",\"MDTUSDT\",\"STMXUSDT\",\"KNCUSDT\",\"REPUSDT\",\"LRCUSDT\",\"PNTUSDT\",\"USDTUAH\",\"COMPUSDT\",\"USDTBIDR\",\"BKRWUSDT\",\"SCUSDT\",\"ZENUSDT\",\"SNXUSDT\",\"ETHUPUSDT\",\"ETHDOWNUSDT\",\"ADAUPUSDT\",\"ADADOWNUSDT\",\"LINKUPUSDT\",\"LINKDOWNUSDT\",\"VTHOUSDT\",\"DGBUSDT\",\"GBPUSDT\",\"SXPUSDT\",\"MKRUSDT\",\"DAIUSDT\",\"DCRUSDT\",\"STORJUSDT\",\"BNBUPUSDT\",\"BNBDOWNUSDT\",\"XTZUPUSDT\",\"XTZDOWNUSDT\",\"USDTBKRW\",\"MANAUSDT\",\"AUDUSDT\",\"YFIUSDT\",\"BALUSDT\",\"BLZUSDT\",\"IRISUSDT\",\"KMDUSDT\",\"USDTDAI\",\"JSTUSDT\",\"SRMUSDT\",\"ANTUSDT\",\"CRVUSDT\",\"SANDUSDT\",\"OCEANUSDT\",\"NMRUSDT\",\"DOTUSDT\",\"LUNAUSDT\",\"RSRUSDT\",\"PAXGUSDT\",\"WNXMUSDT\",\"TRBUSDT\",\"BZRXUSDT\",\"SUSHIUSDT\",\"YFIIUSDT\",\"KSMUSDT\",\"EGLDUSDT\",\"DIAUSDT\",\"RUNEUSDT\",\"FIOUSDT\",\"UMAUSDT\",\"EOSUPUSDT\",\"EOSDOWNUSDT\",\"TRXUPUSDT\",\"TRXDOWNUSDT\",\"XRPUPUSDT\",\"XRPDOWNUSDT\",\"DOTUPUSDT\",\"DOTDOWNUSDT\",\"USDTNGN\",\"BELUSDT\",\"WINGUSDT\",\"LTCUPUSDT\",\"LTCDOWNUSDT\",\"UNIUSDT\",\"NBSUSDT\",\"OXTUSDT\",\"SUNUSDT\",\"AVAXUSDT\",\"HNTUSDT\",\"FLMUSDT\",\"UNIUPUSDT\",\"UNIDOWNUSDT\",\"ORNUSDT\",\"UTKUSDT\",\"XVSUSDT\",\"ALPHAUSDT\",\"USDTBRL\",\"AAVEUSDT\",\"NEARUSDT\",\"SXPUPUSDT\",\"SXPDOWNUSDT\",\"FILUSDT\",\"FILUPUSDT\",\"FILDOWNUSDT\",\"YFIUPUSDT\",\"YFIDOWNUSDT\",\"INJUSDT\",\"AUDIOUSDT\",\"CTKUSDT\",\"BCHUPUSDT\",\"BCHDOWNUSDT\",\"AKROUSDT\",\"AXSUSDT\",\"HARDUSDT\",\"DNTUSDT\",\"STRAXUSDT\",\"UNFIUSDT\",\"ROSEUSDT\",\"AVAUSDT\",\"XEMUSDT\",\"AAVEUPUSDT\",\"AAVEDOWNUSDT\",\"SKLUSDT\",\"SUSDUSDT\",\"SUSHIUPUSDT\",\"SUSHIDOWNUSDT\",\"XLMUPUSDT\",\"XLMDOWNUSDT\",\"GRTUSDT\",\"JUVUSDT\",\"PSGUSDT\",\"USDTBVND\",\"1INCHUSDT\",\"REEFUSDT\",\"OGUSDT\",\"ATMUSDT\",\"ASRUSDT\",\"CELOUSDT\",\"RIFUSDT\",\"BTCSTUSDT\",\"TRUUSDT\",\"CKBUSDT\",\"TWTUSDT\",\"FIROUSDT\",\"LITUSDT\",\"SFPUSDT\"]","msg":"Retrieved exchange information from cache","time":"2021-02-17T18:59:51.004Z","v":0}
```

**Comment by kaziqta** [comment]
Nevermind, deployed using tag 0.0.52, dunno why with latest was failing.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
