### ISSUE TITLE
Execution failed Code: -2010

### ISSUE THREAD

**Issue by itjwd-works** [chrisleekr/binance-trading-bot#165]
Hi to All,
I was trying to find what is the meaning of Code: -2010?

Stop price would trigger immediately.```Stack:```Error: Stop price would trigger immediately.
    at /srv/node_modules/binance-api-node/dist/http-client.js:93:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async execute (/srv/dist/server.js:1:18904)
    at async execute (/srv/dist/server.js:1:5317)
    at async CronJob.<anonymous> (/srv/dist/server.js:1:22789)

**Comment by chrisleekr** [comment]
That means exactly as said. Are you testing in the testnet?
I often see that message in the testnet, not in live.

**Comment by itjwd-works** [comment]
I'm on live, and I made one buy order successfully.
Then when it triggers to sell order then the error came out.

**Comment by itjwd-works** [comment]
Candle
Interval: 1m
Limit: 60

Sell
Trigger: 1.3
Stop: 1.25
Limit: 1.24

**Comment by chrisleekr** [comment]
@itjwd-works 
Your sell configuration is wrong. Read README again, please - https://github.com/chrisleekr/binance-trading-bot#sell-signal

**Comment by chrisleekr** [comment]
This will be a good issue for others when they have the same issue. :)

If you can, please add to Wiki, so others can refer your story - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting

Thanks!

**Comment by itjwd-works** [comment]
Sure, will do that.
