### ISSUE TITLE
Indicator data is not retrieved, wait for cache

### ISSUE THREAD

**Issue by 556isback** [chrisleekr/binance-trading-bot#177]
[https://github.com/chrisleekr/binance-trading-bot/issues/176#issuecomment-841257856](url)
After running the script @chrisleekr provide above the link, here is the log
```
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"API logger loaded","time":"2021-05-14T14:30:46.834Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"connected to the server","time":"2021-05-14T14:30:47.324Z","v":0}
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"Received: {\"e\":\"kline\",\"E\":1621002647335,\"s\":\"BTCUSDT\",\"k\":{\"t\":1621002600000,\"T\":1621002659999,\"s\":\"BTCUSDT\",\"i\":\"1m\",\"f\":832813306,\"L\":832814493,\"o\":\"50564.54000000\",\"c\":\"50618.04000000\",\"h\":\"50659.72000000\",\"l\":\"50564.53000000\",\"v\":\"50.02099500\",\"n\":1188,\"x\":false,\"q\":\"2532187.49764185\",\"V\":\"34.07576700\",\"Q\":\"1724899.90064471\",\"B\":\"0\"}}","time":"2021-05-14T14:30:47.365Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"Received: {\"e\":\"kline\",\"E\":1621002649335,\"s\":\"BTCUSDT\",\"k\":{\"t\":1621002600000,\"T\":1621002659999,\"s\":\"BTCUSDT\",\"i\":\"1m\",\"f\":832813306,\"L\":832814544,\"o\":\"50564.54000000\",\"c\":\"50617.78000000\",\"h\":\"50659.72000000\",\"l\":\"50564.53000000\",\"v\":\"51.32702100\",\"n\":1239,\"x\":false,\"q\":\"2598291.93832258\",\"V\":\"35.30167300\",\"Q\":\"1786949.10969047\",\"B\":\"0\"}}","time":"2021-05-14T14:30:49.362Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"Received: {\"e\":\"kline\",\"E\":1621002651349,\"s\":\"BTCUSDT\",\"k\":{\"t\":1621002600000,\"T\":1621002659999,\"s\":\"BTCUSDT\",\"i\":\"1m\",\"f\":832813306,\"L\":832814753,\"o\":\"50564.54000000\",\"c\":\"50608.39000000\",\"h\":\"50659.72000000\",\"l\":\"50564.53000000\",\"v\":\"54.15385500\",\"n\":1448,\"x\":false,\"q\":\"2741358.61970619\",\"V\":\"35.63802200\",\"Q\":\"1803972.42205735\",\"B\":\"0\"}}","time":"2021-05-14T14:30:51.376Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"Received: {\"e\":\"kline\",\"E\":1621002653383,\"s\":\"BTCUSDT\",\"k\":{\"t\":1621002600000,\"T\":1621002659999,\"s\":\"BTCUSDT\",\"i\":\"1m\",\"f\":832813306,\"L\":832814795,\"o\":\"50564.54000000\",\"c\":\"50609.75000000\",\"h\":\"50659.72000000\",\"l\":\"50564.53000000\",\"v\":\"54.82060600\",\"n\":1490,\"x\":false,\"q\":\"2775098.25731684\",\"V\":\"35.90143100\",\"Q\":\"1817301.84472415\",\"B\":\"0\"}}","time":"2021-05-14T14:30:53.410Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
{"name":"binance-api","version":"0.0.65","hostname":"back556","pid":11374,"level":30,"msg":"Received: {\"e\":\"kline\",\"E\":1621002655539,\"s\":\"BTCUSDT\",\"k\":{\"t\":1621002600000,\"T\":1621002659999,\"s\":\"BTCUSDT\",\"i\":\"1m\",\"f\":832813306,\"L\":832814832,\"o\":\"50564.54000000\",\"c\":\"50604.40000000\",\"h\":\"50659.72000000\",\"l\":\"50564.53000000\",\"v\":\"56.15091000\",\"n\":1527,\"x\":false,\"q\":\"2842419.03787986\",\"V\":\"36.56562200\",\"Q\":\"1850912.74858328\",\"B\":\"0\"}}","time":"2021-05-14T14:30:55.574Z","v":0}
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
[ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis binance-redis:6379
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
```

**Comment by chrisleekr** [comment]
You need to use `docker-compose.server.yml`

If you are using PR #77, please follow this https://github.com/chrisleekr/binance-trading-bot/pull/77#issue-608384137

**Comment by 556isback** [comment]
OK...
I got it up and running now on production mode, thanks for the instruction
