### ISSUE TITLE
Error: getaddrinfo ENOTFOUND binance-redis

### ISSUE THREAD

**Issue by rafaelwood** [chrisleekr/binance-trading-bot#187]
Hi, first of all thanks a lot for this trading bot. I'm trying to push a copy on heroku but i'm running in the following issue:

```
2021-05-18T19:22:58.473830+00:00 heroku[web.1]: Starting process with command `npm start`
2021-05-18T19:23:02.937660+00:00 app[web.1]: 
2021-05-18T19:23:02.937732+00:00 app[web.1]: > binance-trading-bot@0.0.65 start /srv
2021-05-18T19:23:02.937734+00:00 app[web.1]: > node dist/server.js
2021-05-18T19:23:02.937734+00:00 app[web.1]: 
2021-05-18T19:23:03.171410+00:00 app[web.1]: {"name":"binance-api","version":"0.0.65","hostname":"cf6372ef-3114-48c4-98a2-<REDACTED>","pid":15,"level":30,"NODE_ENV":"production","msg":"API logger loaded","time":"2021-05-18T19:23:03.170Z","v":0}
2021-05-18T19:23:03.627769+00:00 app[web.1]: {"name":"binance-api","version":"0.0.65","hostname":"cf6372ef-3114-48c4-98a2-<REDACTED>","pid":15,"helper":"mongo","level":30,"uri":"mongodb://binance-mongo:27017/?poolSize=20&retryWrites=true&writeConcern=majority","msg":"Connecting mongodb","time":"2021-05-18T19:23:03.627Z","v":0}
2021-05-18T19:23:03.676690+00:00 app[web.1]: [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis
2021-05-18T19:23:03.676692+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2021-05-18T19:23:03.732901+00:00 app[web.1]: [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis
2021-05-18T19:23:03.732903+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2021-05-18T19:23:03.836165+00:00 app[web.1]: [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis
2021-05-18T19:23:03.836166+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2021-05-18T19:23:03.988505+00:00 app[web.1]: [ioredis] Unhandled error event: Error: getaddrinfo ENOTFOUND binance-redis
2021-05-18T19:23:03.988518+00:00 app[web.1]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
2021-05-18T19:23:33.650636+00:00 app[web.1]: {"name":"binance-api","version":"0.0.65","hostname":"cf6372ef-3114-48c4-98a2-<REDACTED>","pid":15,"helper":"mongo","level":50,"e":{"name":"MongoServerSelectionError","reason":{"type":"Unknown","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null}},"msg":"Error on connecting to mongodb","time":"2021-05-18T19:23:33.650Z","v":0}
2021-05-18T19:23:33.773467+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2021-05-18T19:23:33.779254+00:00 app[web.1]: npm ERR! errno 1
2021-05-18T19:23:33.808838+00:00 app[web.1]: npm ERR! binance-trading-bot@0.0.65 start: `node dist/server.js`
2021-05-18T19:23:33.809177+00:00 app[web.1]: npm ERR! Exit status 1
2021-05-18T19:23:33.810341+00:00 app[web.1]: npm ERR! 
2021-05-18T19:23:33.810616+00:00 app[web.1]: npm ERR! Failed at the binance-trading-bot@0.0.65 start script.
2021-05-18T19:23:33.810907+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2021-05-18T19:23:33.885532+00:00 app[web.1]: 
2021-05-18T19:23:33.887369+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2021-05-18T19:23:33.887581+00:00 app[web.1]: npm ERR!     /srv/.npm/_logs/2021-05-18T19_23_33_812Z-debug.log
2021-05-18T19:23:33.964207+00:00 heroku[web.1]: Process exited with status 1
2021-05-18T19:23:34.057098+00:00 heroku[web.1]: State changed from starting to crashed
```
Everything works fine on my local machine, anyone encountering a similar issue?

**Comment by chrisleekr** [comment]
Hey @rafaelwood 

Hmm, I never used Heroku before so I am not sure what the issue is.

It looks like Redis container is not running. 

Are they supporting docker compose to run?

If yes, let me know. I want to try putting this button - https://devcenter.heroku.com/articles/heroku-button
