### ISSUE TITLE
Got this problem: Error: connection refused: localtunnel.me:39801

### ISSUE THREAD

**Issue by martip07** [chrisleekr/binance-trading-bot#20]
Hi,

Today I got this problem:

**env:**

- BINANCE_LOCAL_TUNNEL_SUBDOMAIN=default

**docker-compose:**

- target: production-stage

**Error:**

`events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:39801 (check your firewall settings)
    at Socket.<anonymous> (/srv/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on Tunnel instance at:
    at TunnelCluster.<anonymous> (/srv/node_modules/localtunnel/lib/Tunnel.js:96:12)
    at TunnelCluster.emit (events.js:315:20)
    at Socket.<anonymous> (/srv/node_modules/localtunnel/lib/TunnelCluster.js:50:14)
    at Socket.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[nodemon] app crashed - waiting for file changes before starting`

**Comment by chrisleekr** [comment]
Hey @martip07 

It seems local tunnel is having an issue currently. 
You still can access via your <Internal IP>:8080 if you are on the same network.

**Comment by bavinsCo** [comment]
Guys, join the Telegram group to solve problems with each other ..

https://t.me/joinchat/z3cKyYFcx0NiOTA8
