### ISSUE TITLE
Failed execution when the price < 100 sats in trading on xxxBTC pairs

### ISSUE THREAD

**Issue by horizontv3** [chrisleekr/binance-trading-bot#226]
For example, on XVGBTC pair (current price = 0.00000079).

I've got notifications in Slack, as follows:

XVGBTC Buy Action (16:36:19.890): STOP_LOSS_LIMIT
- Order Params:
{
  "symbol": "XVGBTC",
  "side": "buy",
  "type": "STOP_LOSS_LIMIT",
  "quantity": 1233,
  "stopPrice": 8.1e-7,
  "price": 8.1e-7,
  "timeInForce": "GTC"
}

Execution failed (16:36:20.813)
Job: Trailing Trade
Code: -1100
Message:
Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
Stack:
Error: Illegal characters found in parameter 'price'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'.
    at /srv/node_modules/binance-api-node/dist/http-client.js:93:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async execute (/srv/dist/server.js:1:25474)
    at async /srv/dist/server.js:1:3023
    at async Promise.all (index 27)
    at async execute (/srv/dist/server.js:1:1712)
    at async /srv/dist/server.js:1:65227
    at async CronJob.<anonymous> (/srv/dist/server.js:1:65065)

BTW, many thanks for your awesome bot.

**Comment by chrisleekr** [comment]
Oh, that seems a bug you found.

I will fix up when I get time.

**Comment by chrisleekr** [comment]
Closing this as a refactored v1 has been released. It's no longer relevant to the latest code.
