### ISSUE TITLE
Connecting the application

### ISSUE THREAD

**Issue by eladaspis** [chrisleekr/binance-trading-bot#319]
I tried to connect the app but with success.

Log attached:
```
elad@ubuntu:~/Desktop/binance-trading-bot$ sudo docker-compose -f docker-compose.server.yml up -d
[sudo] password for elad: 
binance-redis is up-to-date
Recreating binance-bot ... 
Recreating binance-bot ... done
elad@ubuntu:~/Desktop/binance-trading-bot$ curl http://0.0.0.0:8080
curl: (7) Failed to connect to 0.0.0.0 port 8080: Connection refused
```

**Comment by chrisleekr** [comment]
Strange. Too many people reporting this issue. Let me check.

**Comment by chrisleekr** [comment]
It's working fine on my end. 

Please get the full log and put it here so I can see what is the issue - https://github.com/chrisleekr/binance-trading-bot/wiki/Troubleshooting#how-to-get-the-logs-by-installing-bunyan-npm-package

**Comment by eladaspis** [comment]
I just saw the log and I got the next:

```
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
{"name":"binance-api","version":"0.0.78","hostname":"00d1fd706906","pid":26,"level":30,"NODE_ENV":"production","msg":"API logger loaded","time":"2021-09-15T09:13:40.102Z","v":0}
  error : Error: Missing migration file: 1630845919422-flush-configuration-cache.js
Error: Missing migration file: 1630845919422-flush-configuration-cache.js
    at /srv/node_modules/migrate/lib/load-migrations.js:57:44
    at Array.forEach (<anonymous>)
    at /srv/node_modules/migrate/lib/load-migrations.js:55:44
    at FSReqCallback.oncomplete (fs.js:180:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-trading-bot@0.0.78 migrate:up: `migrate up --store=/srv/mongo-state-storage.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-trading-bot@0.0.78 migrate:up script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-15T09_13_40_151Z-debug.log
```

**Comment by chrisleekr** [comment]
How did you run your bot? 

Have you used docker-compose.server.yml?

```
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d
```

**Comment by eladaspis** [comment]
yes

**Comment by eladaspis** [comment]
Now I got this message:

```
elad@ubuntu:~/Desktop/binance-trading-bot$ docker-compose -f docker-compose.server.yml pull
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/elad/.local/lib/python3.8/site-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
elad@ubuntu:~/Desktop/binance-trading-bot$ docker-compose -f docker-compose.server.yml up -d
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/elad/.local/lib/python3.8/site-packages/pkg_resources.py", line 1479, in <module>
    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
```

**Comment by chrisleekr** [comment]
> AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

That is nothing to do with the bot. 

> Error: Missing migration file: 1630845919422-flush-configuration-cache.js

If you just pulled the image, then the latest image should not have this migration. 
Because that migration is just added to the master.

Is it your first-time setup?

**Comment by eladaspis** [comment]
Its my first-time setup. I pulled it before.

**Comment by chrisleekr** [comment]
Ok, let's prune the image and try again.

```bash
$ docker system prune --volumes -a 
```
Note that this will remove all of your docker container volume and images. 

```bash
docker-compose -f docker-compose.server.yml pull
docker-compose -f docker-compose.server.yml up -d
```

**Comment by eladaspis** [comment]
Great.
Thank you so much!!
Shold I close the case?

**Comment by chrisleekr** [comment]
Yes please.
