### ISSUE TITLE
No trading view after login on server.yml

### ISSUE THREAD

**Issue by atol71** [chrisleekr/binance-trading-bot#381]
I made a fresh install with:
git pull
docker-compose server.yml pull
docker-compose server.yml up -d

No trading view! Password query works but after that there is no trading view on latest release. Tried on localhost:8080 with same results. How would one debug this?

**Comment by Rayn0r** [comment]
Please have a look into issue #368. I described how to revert back to the previous version.

**Comment by chrisleekr** [comment]
@atol71 

How does it show in the frontend? Can you provide a full screenshot?

And can you check the log for `tradingview` container?

```
docker logs tradingview -f --tail=100
```

Is there a new request coming through?

**Comment by Rayn0r** [comment]
This is the output of `docker logs tradingview --tail=100 > tradingbot.log 2>&1` on v0.0.84:
```
{'CRYPTO', ('BINANCE:FTMBUSD',), '30m'} {'BINANCE:FTMBUSD': {'summary': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 9, 'SELL': 7, 'NEUTRAL': 10}, 'time': '2021-10-31T07:25:05.171834', 'oscillators': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 1, 'SELL': 1, 'NEUTRAL': 9, 'COMPUTE': {'RSI': 'NEUTRAL', 'STOCH.K': 'NEUTRAL', 'CCI': 'NEUTRAL', 'ADX': 'NEUTRAL', 'AO': 'NEUTRAL', 'Mom': 'SELL', 'MACD': 'BUY', 'Stoch.RSI': 'NEUTRAL', 'W%R': 'NEUTRAL', 'BBP': 'NEUTRAL', 'UO': 'NEUTRAL'}}, 'moving_averages': {'RECOMMENDATION': 'BUY', 'BUY': 8, 'SELL': 6, 'NEUTRAL': 1, 'COMPUTE': {'EMA10': 'BUY', 'SMA10': 'BUY', 'EMA20': 'BUY', 'SMA20': 'BUY', 'EMA30': 'BUY', 'SMA30': 'BUY', 'EMA50': 'SELL', 'SMA50': 'SELL', 'EMA100': 'SELL', 'SMA100': 'SELL', 'EMA200': 'SELL', 'SMA200': 'SELL', 'Ichimoku': 'NEUTRAL', 'VWMA': 'BUY', 'HullMA': 'BUY'}}, 'indicators': {'Recommend.Other': 0, 'Recommend.All': 0.06666667, 'Recommend.MA': 0.13333333, 'RSI': 51.01910641, 'RSI[1]': 48.01050183, 'Stoch.K': 50.73769737, 'Stoch.D': 45.87666565, 'Stoch.K[1]': 44.2112095, 'Stoch.D[1]': 46.78390434, 'CCI20': 108.81529082, 'CCI20[1]': 42.41501776, 'ADX': 13.87566886, 'ADX+DI': 20.59094714, 'ADX-DI': 18.60101762, 'ADX+DI[1]': 15.34044933, 'ADX-DI[1]': 21.0121524, 'AO': -0.02411382, 'AO[1]': -0.02957794, 'Mom': 0.0128, 'Mom[1]': 0.0428, 'MACD.macd': -0.01715567, 'MACD.signal': -0.02505592, 'Rec.Stoch.RSI': 0, 'Stoch.RSI.K': 87.64942802, 'Rec.WR': 0, 'W.R': -29.32692308, 'Rec.BBPower': 0, 'BBPower': 0.03223109, 'Rec.UO': 0, 'UO': 51.51839997, 'close': 2.7009, 'EMA5': 2.67961812, 'SMA5': 2.67424, 'EMA10': 2.67482369, 'SMA10': 2.6678, 'EMA20': 2.68277762, 'SMA20': 2.66788, 'EMA30': 2.69947827, 'SMA30': 2.69141, 'EMA50': 2.73839594, 'SMA50': 2.737728, 'EMA100': 2.82265129, 'SMA100': 2.845286, 'EMA200': 2.8934152, 'SMA200': 2.9769115, 'Rec.Ichimoku': 0, 'Ichimoku.BLine': 2.70605, 'Rec.VWMA': 1, 'VWMA': 2.66543021, 'Rec.HullMA9': 1, 'HullMA9': 2.68099556, 'Pivot.M.Classic.S3': 1.17916667, 'Pivot.M.Classic.S2': 1.86816667, 'Pivot.M.Classic.S1': 2.28433333, 'Pivot.M.Classic.Middle': 2.55716667, 'Pivot.M.Classic.R1': 2.97333333, 'Pivot.M.Classic.R2': 3.24616667, 'Pivot.M.Classic.R3': 3.93516667, 'Pivot.M.Fibonacci.S3': 1.86816667, 'Pivot.M.Fibonacci.S2': 2.13136467, 'Pivot.M.Fibonacci.S1': 2.29396867, 'Pivot.M.Fibonacci.Middle': 2.55716667, 'Pivot.M.Fibonacci.R1': 2.82036467, 'Pivot.M.Fibonacci.R2': 2.98296867, 'Pivot.M.Fibonacci.R3': 3.24616667, 'Pivot.M.Camarilla.S3': 2.511025, 'Pivot.M.Camarilla.S2': 2.57418333, 'Pivot.M.Camarilla.S1': 2.63734167, 'Pivot.M.Camarilla.Middle': 2.55716667, 'Pivot.M.Camarilla.R1': 2.76365833, 'Pivot.M.Camarilla.R2': 2.82681667, 'Pivot.M.Camarilla.R3': 2.889975, 'Pivot.M.Woodie.S3': 1.6667, 'Pivot.M.Woodie.S2': 1.90385, 'Pivot.M.Woodie.S1': 2.3557, 'Pivot.M.Woodie.Middle': 2.59285, 'Pivot.M.Woodie.R1': 3.0447, 'Pivot.M.Woodie.R2': 3.28185, 'Pivot.M.Woodie.R3': 3.7337, 'Pivot.M.Demark.S1': 2.42075, 'Pivot.M.Demark.Middle': 2.625375, 'Pivot.M.Demark.R1': 3.10975, 'open': 2.6793, 'P.SAR': 2.6, 'BB.lower': 2.6204534, 'BB.upper': 2.7153066, 'AO[2]': -0.03574618, 'volume': 430641, 'change': 0.78361133, 'low': 2.6534, 'high': 2.73}}}
Process _handle_symbols
Process _handle_symbols
{'CRYPTO', ('BINANCE:FTMBUSD',), '30m'} {'BINANCE:FTMBUSD': {'summary': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 9, 'SELL': 7, 'NEUTRAL': 10}, 'time': '2021-10-31T07:25:06.745168', 'oscillators': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 1, 'SELL': 1, 'NEUTRAL': 9, 'COMPUTE': {'RSI': 'NEUTRAL', 'STOCH.K': 'NEUTRAL', 'CCI': 'NEUTRAL', 'ADX': 'NEUTRAL', 'AO': 'NEUTRAL', 'Mom': 'SELL', 'MACD': 'BUY', 'Stoch.RSI': 'NEUTRAL', 'W%R': 'NEUTRAL', 'BBP': 'NEUTRAL', 'UO': 'NEUTRAL'}}, 'moving_averages': {'RECOMMENDATION': 'BUY', 'BUY': 8, 'SELL': 6, 'NEUTRAL': 1, 'COMPUTE': {'EMA10': 'BUY', 'SMA10': 'BUY', 'EMA20': 'BUY', 'SMA20': 'BUY', 'EMA30': 'BUY', 'SMA30': 'BUY', 'EMA50': 'SELL', 'SMA50': 'SELL', 'EMA100': 'SELL', 'SMA100': 'SELL', 'EMA200': 'SELL', 'SMA200': 'SELL', 'Ichimoku': 'NEUTRAL', 'VWMA': 'BUY', 'HullMA': 'BUY'}}, 'indicators': {'Recommend.Other': 0, 'Recommend.All': 0.06666667, 'Recommend.MA': 0.13333333, 'RSI': 51.01910641, 'RSI[1]': 48.01050183, 'Stoch.K': 50.73769737, 'Stoch.D': 45.87666565, 'Stoch.K[1]': 44.2112095, 'Stoch.D[1]': 46.78390434, 'CCI20': 108.81529082, 'CCI20[1]': 42.41501776, 'ADX': 13.87566886, 'ADX+DI': 20.59094714, 'ADX-DI': 18.60101762, 'ADX+DI[1]': 15.34044933, 'ADX-DI[1]': 21.0121524, 'AO': -0.02411382, 'AO[1]': -0.02957794, 'Mom': 0.0128, 'Mom[1]': 0.0428, 'MACD.macd': -0.01715567, 'MACD.signal': -0.02505592, 'Rec.Stoch.RSI': 0, 'Stoch.RSI.K': 87.64942802, 'Rec.WR': 0, 'W.R': -29.32692308, 'Rec.BBPower': 0, 'BBPower': 0.03223109, 'Rec.UO': 0, 'UO': 51.51839997, 'close': 2.7009, 'EMA5': 2.67961812, 'SMA5': 2.67424, 'EMA10': 2.67482369, 'SMA10': 2.6678, 'EMA20': 2.68277762, 'SMA20': 2.66788, 'EMA30': 2.69947827, 'SMA30': 2.69141, 'EMA50': 2.73839594, 'SMA50': 2.737728, 'EMA100': 2.82265129, 'SMA100': 2.845286, 'EMA200': 2.8934152, 'SMA200': 2.9769115, 'Rec.Ichimoku': 0, 'Ichimoku.BLine': 2.70605, 'Rec.VWMA': 1, 'VWMA': 2.66543021, 'Rec.HullMA9': 1, 'HullMA9': 2.68099556, 'Pivot.M.Classic.S3': 1.17916667, 'Pivot.M.Classic.S2': 1.86816667, 'Pivot.M.Classic.S1': 2.28433333, 'Pivot.M.Classic.Middle': 2.55716667, 'Pivot.M.Classic.R1': 2.97333333, 'Pivot.M.Classic.R2': 3.24616667, 'Pivot.M.Classic.R3': 3.93516667, 'Pivot.M.Fibonacci.S3': 1.86816667, 'Pivot.M.Fibonacci.S2': 2.13136467, 'Pivot.M.Fibonacci.S1': 2.29396867, 'Pivot.M.Fibonacci.Middle': 2.55716667, 'Pivot.M.Fibonacci.R1': 2.82036467, 'Pivot.M.Fibonacci.R2': 2.98296867, 'Pivot.M.Fibonacci.R3': 3.24616667, 'Pivot.M.Camarilla.S3': 2.511025, 'Pivot.M.Camarilla.S2': 2.57418333, 'Pivot.M.Camarilla.S1': 2.63734167, 'Pivot.M.Camarilla.Middle': 2.55716667, 'Pivot.M.Camarilla.R1': 2.76365833, 'Pivot.M.Camarilla.R2': 2.82681667, 'Pivot.M.Camarilla.R3': 2.889975, 'Pivot.M.Woodie.S3': 1.6667, 'Pivot.M.Woodie.S2': 1.90385, 'Pivot.M.Woodie.S1': 2.3557, 'Pivot.M.Woodie.Middle': 2.59285, 'Pivot.M.Woodie.R1': 3.0447, 'Pivot.M.Woodie.R2': 3.28185, 'Pivot.M.Woodie.R3': 3.7337, 'Pivot.M.Demark.S1': 2.42075, 'Pivot.M.Demark.Middle': 2.625375, 'Pivot.M.Demark.R1': 3.10975, 'open': 2.6793, 'P.SAR': 2.6, 'BB.lower': 2.6204534, 'BB.upper': 2.7153066, 'AO[2]': -0.03574618, 'volume': 430641, 'change': 0.78361133, 'low': 2.6534, 'high': 2.73}}}
Process _handle_symbols
Process _handle_symbols
172.26.0.2 - - [31/Oct/2021 07:25:08] "GET /?symbols=BINANCE%3AFTMBUSD&screener=CRYPTO&interval=30m HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.26.0.2', 60002)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/app/main.py", line 72, in do_GET
    self._handle_symbols(qParsed)
  File "/app/main.py", line 51, in _handle_symbols
    'summary': symbolAnalyse.summary, 'time': symbolAnalyse.time.isoformat(), 'oscillators': symbolAnalyse.oscillators, 'moving_averages': symbolAnalyse.moving_averages, 'indicators': symbolAnalyse.indicators}
AttributeError: 'NoneType' object has no attribute 'summary'
----------------------------------------
172.26.0.2 - - [31/Oct/2021 07:25:12] "GET /?symbols=BINANCE%3AFTMBUSD&screener=CRYPTO&interval=30m HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.26.0.2', 60020)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/app/main.py", line 72, in do_GET
    self._handle_symbols(qParsed)
  File "/app/main.py", line 51, in _handle_symbols
    'summary': symbolAnalyse.summary, 'time': symbolAnalyse.time.isoformat(), 'oscillators': symbolAnalyse.oscillators, 'moving_averages': symbolAnalyse.moving_averages, 'indicators': symbolAnalyse.indicators}
AttributeError: 'NoneType' object has no attribute 'summary'
----------------------------------------
{'CRYPTO', ('BINANCE:FTMBUSD',), '30m'} {'BINANCE:FTMBUSD': {'summary': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 9, 'SELL': 7, 'NEUTRAL': 10}, 'time': '2021-10-31T07:25:08.722406', 'oscillators': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 1, 'SELL': 1, 'NEUTRAL': 9, 'COMPUTE': {'RSI': 'NEUTRAL', 'STOCH.K': 'NEUTRAL', 'CCI': 'NEUTRAL', 'ADX': 'NEUTRAL', 'AO': 'NEUTRAL', 'Mom': 'SELL', 'MACD': 'BUY', 'Stoch.RSI': 'NEUTRAL', 'W%R': 'NEUTRAL', 'BBP': 'NEUTRAL', 'UO': 'NEUTRAL'}}, 'moving_averages': {'RECOMMENDATION': 'BUY', 'BUY': 8, 'SELL': 6, 'NEUTRAL': 1, 'COMPUTE': {'EMA10': 'BUY', 'SMA10': 'BUY', 'EMA20': 'BUY', 'SMA20': 'BUY', 'EMA30': 'BUY', 'SMA30': 'BUY', 'EMA50': 'SELL', 'SMA50': 'SELL', 'EMA100': 'SELL', 'SMA100': 'SELL', 'EMA200': 'SELL', 'SMA200': 'SELL', 'Ichimoku': 'NEUTRAL', 'VWMA': 'BUY', 'HullMA': 'BUY'}}, 'indicators': {'Recommend.Other': 0, 'Recommend.All': 0.06666667, 'Recommend.MA': 0.13333333, 'RSI': 51.01910641, 'RSI[1]': 48.01050183, 'Stoch.K': 50.73769737, 'Stoch.D': 45.87666565, 'Stoch.K[1]': 44.2112095, 'Stoch.D[1]': 46.78390434, 'CCI20': 108.81529082, 'CCI20[1]': 42.41501776, 'ADX': 13.87566886, 'ADX+DI': 20.59094714, 'ADX-DI': 18.60101762, 'ADX+DI[1]': 15.34044933, 'ADX-DI[1]': 21.0121524, 'AO': -0.02411382, 'AO[1]': -0.02957794, 'Mom': 0.0128, 'Mom[1]': 0.0428, 'MACD.macd': -0.01715567, 'MACD.signal': -0.02505592, 'Rec.Stoch.RSI': 0, 'Stoch.RSI.K': 87.64942802, 'Rec.WR': 0, 'W.R': -29.32692308, 'Rec.BBPower': 0, 'BBPower': 0.03223109, 'Rec.UO': 0, 'UO': 51.51839997, 'close': 2.7009, 'EMA5': 2.67961812, 'SMA5': 2.67424, 'EMA10': 2.67482369, 'SMA10': 2.6678, 'EMA20': 2.68277762, 'SMA20': 2.66788, 'EMA30': 2.69947827, 'SMA30': 2.69141, 'EMA50': 2.73839594, 'SMA50': 2.737728, 'EMA100': 2.82265129, 'SMA100': 2.845286, 'EMA200': 2.8934152, 'SMA200': 2.9769115, 'Rec.Ichimoku': 0, 'Ichimoku.BLine': 2.70605, 'Rec.VWMA': 1, 'VWMA': 2.66543021, 'Rec.HullMA9': 1, 'HullMA9': 2.68099556, 'Pivot.M.Classic.S3': 1.17916667, 'Pivot.M.Classic.S2': 1.86816667, 'Pivot.M.Classic.S1': 2.28433333, 'Pivot.M.Classic.Middle': 2.55716667, 'Pivot.M.Classic.R1': 2.97333333, 'Pivot.M.Classic.R2': 3.24616667, 'Pivot.M.Classic.R3': 3.93516667, 'Pivot.M.Fibonacci.S3': 1.86816667, 'Pivot.M.Fibonacci.S2': 2.13136467, 'Pivot.M.Fibonacci.S1': 2.29396867, 'Pivot.M.Fibonacci.Middle': 2.55716667, 'Pivot.M.Fibonacci.R1': 2.82036467, 'Pivot.M.Fibonacci.R2': 2.98296867, 'Pivot.M.Fibonacci.R3': 3.24616667, 'Pivot.M.Camarilla.S3': 2.511025, 'Pivot.M.Camarilla.S2': 2.57418333, 'Pivot.M.Camarilla.S1': 2.63734167, 'Pivot.M.Camarilla.Middle': 2.55716667, 'Pivot.M.Camarilla.R1': 2.76365833, 'Pivot.M.Camarilla.R2': 2.82681667, 'Pivot.M.Camarilla.R3': 2.889975, 'Pivot.M.Woodie.S3': 1.6667, 'Pivot.M.Woodie.S2': 1.90385, 'Pivot.M.Woodie.S1': 2.3557, 'Pivot.M.Woodie.Middle': 2.59285, 'Pivot.M.Woodie.R1': 3.0447, 'Pivot.M.Woodie.R2': 3.28185, 'Pivot.M.Woodie.R3': 3.7337, 'Pivot.M.Demark.S1': 2.42075, 'Pivot.M.Demark.Middle': 2.625375, 'Pivot.M.Demark.R1': 3.10975, 'open': 2.6793, 'P.SAR': 2.6, 'BB.lower': 2.6204534, 'BB.upper': 2.7153066, 'AO[2]': -0.03574618, 'volume': 430641, 'change': 0.78361133, 'low': 2.6534, 'high': 2.73}}}
Process _handle_symbols
Process _handle_symbols
{'CRYPTO', ('BINANCE:FTMBUSD',), '30m'} {'BINANCE:FTMBUSD': {'summary': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 9, 'SELL': 7, 'NEUTRAL': 10}, 'time': '2021-10-31T07:25:12.187206', 'oscillators': {'RECOMMENDATION': 'NEUTRAL', 'BUY': 1, 'SELL': 1, 'NEUTRAL': 9, 'COMPUTE': {'RSI': 'NEUTRAL', 'STOCH.K': 'NEUTRAL', 'CCI': 'NEUTRAL', 'ADX': 'NEUTRAL', 'AO': 'NEUTRAL', 'Mom': 'SELL', 'MACD': 'BUY', 'Stoch.RSI': 'NEUTRAL', 'W%R': 'NEUTRAL', 'BBP': 'NEUTRAL', 'UO': 'NEUTRAL'}}, 'moving_averages': {'RECOMMENDATION': 'BUY', 'BUY': 8, 'SELL': 6, 'NEUTRAL': 1, 'COMPUTE': {'EMA10': 'BUY', 'SMA10': 'BUY', 'EMA20': 'BUY', 'SMA20': 'BUY', 'EMA30': 'BUY', 'SMA30': 'BUY', 'EMA50': 'SELL', 'SMA50': 'SELL', 'EMA100': 'SELL', 'SMA100': 'SELL', 'EMA200': 'SELL', 'SMA200': 'SELL', 'Ichimoku': 'NEUTRAL', 'VWMA': 'BUY', 'HullMA': 'BUY'}}, 'indicators': {'Recommend.Other': 0, 'Recommend.All': 0.06666667, 'Recommend.MA': 0.13333333, 'RSI': 51.01910641, 'RSI[1]': 48.01050183, 'Stoch.K': 50.73769737, 'Stoch.D': 45.87666565, 'Stoch.K[1]': 44.2112095, 'Stoch.D[1]': 46.78390434, 'CCI20': 108.81529082, 'CCI20[1]': 42.41501776, 'ADX': 13.87566886, 'ADX+DI': 20.59094714, 'ADX-DI': 18.60101762, 'ADX+DI[1]': 15.34044933, 'ADX-DI[1]': 21.0121524, 'AO': -0.02411382, 'AO[1]': -0.02957794, 'Mom': 0.0128, 'Mom[1]': 0.0428, 'MACD.macd': -0.01715567, 'MACD.signal': -0.02505592, 'Rec.Stoch.RSI': 0, 'Stoch.RSI.K': 87.64942802, 'Rec.WR': 0, 'W.R': -29.32692308, 'Rec.BBPower': 0, 'BBPower': 0.03223109, 'Rec.UO': 0, 'UO': 51.51839997, 'close': 2.6995, 'EMA5': 2.67961812, 'SMA5': 2.67424, 'EMA10': 2.67482369, 'SMA10': 2.6678, 'EMA20': 2.68277762, 'SMA20': 2.66788, 'EMA30': 2.69947827, 'SMA30': 2.69141, 'EMA50': 2.73839594, 'SMA50': 2.737728, 'EMA100': 2.82265129, 'SMA100': 2.845286, 'EMA200': 2.8934152, 'SMA200': 2.9769115, 'Rec.Ichimoku': 0, 'Ichimoku.BLine': 2.70605, 'Rec.VWMA': 1, 'VWMA': 2.66543021, 'Rec.HullMA9': 1, 'HullMA9': 2.68099556, 'Pivot.M.Classic.S3': 1.17916667, 'Pivot.M.Classic.S2': 1.86816667, 'Pivot.M.Classic.S1': 2.28433333, 'Pivot.M.Classic.Middle': 2.55716667, 'Pivot.M.Classic.R1': 2.97333333, 'Pivot.M.Classic.R2': 3.24616667, 'Pivot.M.Classic.R3': 3.93516667, 'Pivot.M.Fibonacci.S3': 1.86816667, 'Pivot.M.Fibonacci.S2': 2.13136467, 'Pivot.M.Fibonacci.S1': 2.29396867, 'Pivot.M.Fibonacci.Middle': 2.55716667, 'Pivot.M.Fibonacci.R1': 2.82036467, 'Pivot.M.Fibonacci.R2': 2.98296867, 'Pivot.M.Fibonacci.R3': 3.24616667, 'Pivot.M.Camarilla.S3': 2.511025, 'Pivot.M.Camarilla.S2': 2.57418333, 'Pivot.M.Camarilla.S1': 2.63734167, 'Pivot.M.Camarilla.Middle': 2.55716667, 'Pivot.M.Camarilla.R1': 2.76365833, 'Pivot.M.Camarilla.R2': 2.82681667, 'Pivot.M.Camarilla.R3': 2.889975, 'Pivot.M.Woodie.S3': 1.6667, 'Pivot.M.Woodie.S2': 1.90385, 'Pivot.M.Woodie.S1': 2.3557, 'Pivot.M.Woodie.Middle': 2.59285, 'Pivot.M.Woodie.R1': 3.0447, 'Pivot.M.Woodie.R2': 3.28185, 'Pivot.M.Woodie.R3': 3.7337, 'Pivot.M.Demark.S1': 2.42075, 'Pivot.M.Demark.Middle': 2.625375, 'Pivot.M.Demark.R1': 3.10975, 'open': 2.6793, 'P.SAR': 2.6, 'BB.lower': 2.6204534, 'BB.upper': 2.7153066, 'AO[2]': -0.03574618, 'volume': 432385, 'change': 0.73137057, 'low': 2.6534, 'high': 2.73}}}
Process _handle_symbols
172.26.0.2 - - [31/Oct/2021 07:25:13] "GET /?symbols=BINANCE%3AFTMBUSD&screener=CRYPTO&interval=30m HTTP/1.1" 200 -
Process _handle_symbols
----------------------------------------
Exception occurred during processing of request from ('172.26.0.2', 60038)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/app/main.py", line 72, in do_GET
    self._handle_symbols(qParsed)
  File "/app/main.py", line 51, in _handle_symbols
    'summary': symbolAnalyse.summary, 'time': symbolAnalyse.time.isoformat(), 'oscillators': symbolAnalyse.oscillators, 'moving_averages': symbolAnalyse.moving_averages, 'indicators': symbolAnalyse.indicators}
AttributeError: 'NoneType' object has no attribute 'summary'
----------------------------------------
172.26.0.2 - - [31/Oct/2021 07:25:15] "GET /?symbols=BINANCE%3AFTMBUSD&screener=CRYPTO&interval=30m HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('172.26.0.2', 60054)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/app/main.py", line 72, in do_GET
    self._handle_symbols(qParsed)
  File "/app/main.py", line 51, in _handle_symbols
    'summary': symbolAnalyse.summary, 'time': symbolAnalyse.time.isoformat(), 'oscillators': symbolAnalyse.oscillators, 'moving_averages': symbolAnalyse.moving_averages, 'indicators': symbolAnalyse.indicators}
AttributeError: 'NoneType' object has no attribute 'summary'
----------------------------------------

```

**Comment by chrisleekr** [comment]
Yap, I was just able to replicate that issue. Let me find a solution for it.

**Comment by chrisleekr** [comment]
@atol71 I have refactored TradingView with Flask.

Please see the PR and test please - https://github.com/chrisleekr/binance-trading-bot/pull/383

**Comment by atol71** [comment]
I will see this issue later in evening due not able to do so right now.

**Comment by atol71** [comment]
I run the bunyan log and the trading view seems to run perfectly in background. It is not just displaying any graphical output on browser.

**Comment by chrisleekr** [comment]
@atol71 

That is not related to TradingView issue.

Check your developer inspector's console. 
If there is an error with settings, then follow these steps - https://github.com/chrisleekr/binance-trading-bot/releases/tag/v0.0.83

**Comment by BramFr** [comment]
Did you manually change your yml settings ?
Do you have 4 containers running?
When you used `git pull` did you see any message?

You can also use this command for reset everything local `git reset --hard origin/master` beware you can lost your DB settings with this. After your `docker-compose server.yml up -d` command
