### ISSUE TITLE
binance-bot stops serving from compose

### ISSUE THREAD

**Issue by mstumberger** [chrisleekr/binance-trading-bot#407]
## Version

Running Version:
v0.0.85
(55d7027)
Latest Version:
v0.0.85

## Description
![ss](https://user-images.githubusercontent.com/17837422/148663695-aad38ce5-668b-44f7-b375-ae67de19b352.png)

When running server compose file binance-bot image stops serving frontend.
When looking at logs I can see this error.

`docker-compose -f docker-compose.server.yml logs --tail=12 binance-bot`

```
binance-bot      | (node:47) UnhandledPromiseRejectionWarning: SyntaxError: Invalid or unexpected token
binance-bot      |     at _default (/srv/node_modules/binance-api-node/dist/open-websocket.js:15:13)
binance-bot      |     at /srv/node_modules/binance-api-node/dist/websocket.js:180:40
binance-bot      |     at Array.map (<anonymous>)
binance-bot      |     at Object.candles (/srv/node_modules/binance-api-node/dist/websocket.js:179:62)
binance-bot      |     at b (/srv/dist/server.js:1:109583)
binance-bot      |     at async p (/srv/dist/server.js:1:109847)
binance-bot      |     at async runBinance (/srv/dist/server.js:1:110795)
binance-bot      |     at async /srv/dist/server.js:1:118906
binance-bot      | (Use `node --trace-warnings ...` to show where the warning was created)
binance-bot      | (node:47) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
binance-bot      | (node:47) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce

1. run `docker-compose -f docker-compose.server.yml up -d`
2. Wait for frontend to stop responding (usually it happens in range of 24 hours)
3. See error

**Comment by mstumberger** [comment]
dumped mongo persistent storage and it started working but trading data was lost :(
