### ISSUE TITLE
App crashed - maybe tunnel related

### ISSUE THREAD

**Issue by Maxoos** [chrisleekr/binance-trading-bot#44]
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: localtunnel.me:44027 (check your firewall settings)
    at Socket.<anonymous> (/srv/node_modules/localtunnel/lib/TunnelCluster.js:52:11)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on Tunnel instance at:
    at TunnelCluster.<anonymous> (/srv/node_modules/localtunnel/lib/Tunnel.js:96:12)
    at TunnelCluster.emit (events.js:315:20)
    at Socket.<anonymous> (/srv/node_modules/localtunnel/lib/TunnelCluster.js:50:14)
    at Socket.emit (events.js:315:20)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by chrisleekr** [comment]
@Maxoos Yeah looks like the local tunnel issue. 

You can disable it by setting `BINANCE_LOCAL_TUNNEL_ENABLED` as true.
And access by IP address.

**Comment by Maxoos** [comment]
@chrisleekr Thanks, you mean BINANCE_LOCAL_TUNNEL_ENABLED=false?

**Comment by chrisleekr** [comment]
Woops, yeah, false.

**Comment by Maxoos** [comment]
@chrisleekr roger thank you
