### ISSUE TITLE
Buy Grid Trade not filled after buy order filled

### ISSUE THREAD

**Issue by uhliksk** [chrisleekr/binance-trading-bot#575]
## Version

v0.0.96

## Description

After buy order has been filled, bot got stuck with `...you have enough BTC to sell`.

## To Reproduce

Random issue. I can't reproduce by will.

## Expected Behaviours

All buy orders have to be processed correctly.

## Screenshots

Order on Binance:
![image](https://user-images.githubusercontent.com/37454226/210631589-b9d5cbcc-7f9f-4f65-af29-3211fe4ff8f6.png)

Docker log:
![image](https://user-images.githubusercontent.com/37454226/210632800-85ef8b28-41fc-4fa7-97ec-846221726552.png)

Trade on Binance:
![image](https://user-images.githubusercontent.com/37454226/210631020-6c6ffd94-7f69-409e-9ad3-c1155b21e39e.png)

Docker log:
![image](https://user-images.githubusercontent.com/37454226/210632653-f147823f-ca8f-4109-8493-cb3720755b1b.png)

Bot stuck:
![image](https://user-images.githubusercontent.com/37454226/210630578-7da917d5-102e-49b4-a711-ffc19bbfcad4.png)

## Additional context

Unfortunately it was too late to export log as it passed more than 30 minutes already but I have at least docker log. Interesting thing is there is no event logged at 19:20:16 (18:20:16 UTC) when order has been filled.

**Comment by uhliksk** [comment]
@chrisleekr There is unused `checkOrderExecutePeriod` configuration parameter. Does that mean bot was able to check for orders periodically and this functionality has been removed in the past or was this planned to be implemented in the future?

**Comment by chrisleekr** [comment]
@uhliksk `checkOrderExecutePeriod` was used before implementing WebSocket to receive order notifications.
Now it is deprecated. Should remove this variable from the configuration.


For the issue you raised, two scenarios can be guessed.
1. The filled order event was not received from Binance. So the bot may not record the last buy price.
2. The filled order event was sent from Binance, but the bot ignored processing it.

Unfortunately, it's hard to find out what happened without the log.
If happens again, try to get the log.

By the way, you can now export the log without any issue? So the fix is working?

**Comment by uhliksk** [comment]
@chrisleekr 

> 1. The filled order event was not received from Binance. So the bot may not record the last buy price.
> 2. The filled order event was sent from Binance, but the bot ignored processing it.

Can we check periodically if orders are still present on Binance? Or at least when `enough SYMBOL to sell` is detected the option to set last buy price from last buy order (or orders up to sum of current balance) automatically will be great solution I think. Or for simplicity we can use current price as last buy price if asset is transfered to spot wallet from funding wallet or by Binance Convert. I don't use spot wallet for nothing else but bot trading so everytime there is some balance it should be traded automatically without waiting to put last buy price manually.

> By the way, you can now export the log without any issue? So the fix is working?

Yes, log export is working flawlessly now.

**Comment by uhliksk** [comment]
@chrisleekr

> Yes, log export is working flawlessly now.

But, not working for big logs:

```
{"name":"binance-api","version":"0.0.96","hostname":"94d1c8d5d371","pid":46,"gitHash":"unspecified","level":50,"err":{"message":"Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.","name":"MongoServerError","stack":"MongoServerError: Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.\n    at MessageStream.messageHandler (/srv/node_modules/mongodb/lib/cmap/connection.js:463:30)\n    at MessageStream.emit (events.js:400:28)\n    at processIncomingData (/srv/node_modules/mongodb/lib/cmap/message_stream.js:108:16)\n    at MessageStream._write (/srv/node_modules/mongodb/lib/cmap/message_stream.js:28:9)\n    at writeOrBuffer (internal/streams/writable.js:358:12)\n    at MessageStream.Writable.write (internal/streams/writable.js:303:10)\n    at Socket.ondata (internal/streams/readable.js:731:22)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)","code":96},"msg":"Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.","time":"2023-01-05T15:03:01.125Z","v":0}
```
