### ISSUE TITLE
 Failed authentication JsonWebTokenError: jwt must be provided

### ISSUE THREAD

**Issue by CoooWeee** [chrisleekr/binance-trading-bot#605]
## Version
v0.0.96

## Description
Login does not  work

## To Reproduce

1. Go to login page
2. type in right password
3. hit enter or right arrow
4. See spinner of death

## Expected Behaviours

come to the trading page

## Screenshots

<img width="266" alt="Screenshot 2023-02-18 at 07 21 34" src="https://user-images.githubusercontent.com/46728415/219795926-9375d02b-c606-4f6e-a812-30f5e65cc6d3.png">

## Additional context

```
[2023-02-17T21:13:25.910Z]  INFO: binance-api/46 on 3dd112e48c6c: Verifying authentication (version=0.0.96, gitHash=209d2e0, server=websocket, correlationId=cf7146ed-49ef-4fb9-bcc1-4984f51537ac, tag=verifyAuthenticated, authToken="", jwtSecret=a800dfb1-3bec-41f9-8d95-52d2ad3428ef)
    payload: {
      "command": "latest",
      "authToken": "",
      "data": {
        "page": 1,
        "searchKeyword": "",
        "sortBy": "default",
        "sortByDesc": false,
        "hideInactive": false
      }
    }
[2023-02-17T21:13:25.911Z]  INFO: binance-api/46 on 3dd112e48c6c: Failed authentication (version=0.0.96, gitHash=209d2e0, server=websocket, correlationId=cf7146ed-49ef-4fb9-bcc1-4984f51537ac, tag=verifyAuthenticated)
    JsonWebTokenError: jwt must be provided
        at Object.module.exports [as verify] (/srv/node_modules/jsonwebtoken/verify.js:53:17)
        at verifyAuthenticated (/srv/dist/server.js:1:72767)
        at async WebSocket.<anonymous> (/srv/dist/server.js:1:115209)
    --
    payload: {
      "command": "latest",
      "authToken": "",
      "data": {
        "page": 1,
        "searchKeyword": "",
        "sortBy": "default",
        "sortByDesc": false,
        "hideInactive": false
      }
    }
```

**Comment by CoooWeee** [comment]
I pulled the repository again and did a clean reinstall which solved the issue. Just a reinstall did not fix it. There must have been something wrong with the repository files.
