### ISSUE TITLE
docker image does not start

### ISSUE THREAD

**Issue by viktor-gon** [chrisleekr/binance-trading-bot#663]
## Version

0.0.98

## Description

docker image does not start

## To Reproduce

1. Clone repo
2. docker compose -f docker-compose.server.yml up

binance-bot    | {"name":"binance-api","version":"0.0.98","hostname":"7547c8d8395b","pid":25,"level":30,"NODE_ENV":"production","msg":"API logger loaded","time":"2024-08-19T04:34:34.119Z","v":0}
binance-bot    |   error : Error: Missing migration file: 1664194720480-add-multiple-tradingviews.js
binance-bot    | Error: Missing migration file: 1664194720480-add-multiple-tradingviews.js
binance-bot    |     at /srv/node_modules/migrate/lib/load-migrations.js:57:44
binance-bot    |     at Array.forEach (<anonymous>)
binance-bot    |     at /srv/node_modules/migrate/lib/load-migrations.js:55:44
binance-bot    |     at FSReqCallback.oncomplete (fs.js:180:23)

## Expected Behaviours

Image is starting successfully

**Comment by viktor-gon** [comment]
This resolved a problem
`$ docker-compose -f docker-compose.server.yml down -v
$ docker-compose -f docker-compose.server.yml pull
$ docker-compose -f docker-compose.server.yml up -d`

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by chrisleekr** [comment]
Closing this as a refactored v1 has been released. It's no longer relevant to the latest code.
