### ISSUE TITLE
Failed to load your account information when opens the web page

### ISSUE THREAD

**Issue by sekozzi** [chrisleekr/binance-trading-bot#664]
Hello,

I've got attached error when I ran the bot. I'v checked all of them following requirement. 

You are seeing this error message because of one of the following situations:
You are using TestNet API/Secret for Live Binance.
You are using Live API/Secret for TestNet Binance.
Your API key is revoked/deleted.
Your API key is not permitted to "Enable Reading" and "Enable Spot & Margin Trading".
Your API key is restricted to trusted IP, and your bot is located not in trusted IP.

I see following log line when I checked the binance-bot logs.

{"name":"binance-api","version":"0.0.98","hostname":"4f7c36303b6e","pid":46,"gitHash":"d321990","server":"websocket","payload":{"command":"latest","authToken":"","data":{"page":1,"searchKeyword":"","sortBy":"default","sortByDesc":false,"hideInactive":false}},"correlationId":"a5e4d738-b700-44c0-b0f8-3031279c7ee1","tag":"verifyAuthenticated","level":30,"err":{"message":"jwt must be provided","name":"JsonWebTokenError","stack":"JsonWebTokenError: jwt must be provided\n    at Object.module.exports [as verify] (/srv/node_modules/jsonwebtoken/verify.js:53:17)\n    at verifyAuthenticated (/srv/dist/server.js:1:62133)\n    at async WebSocket.<anonymous> (/srv/dist/server.js:1:105093)"},"msg":"Failed authentication","time":"2024-08-19T00:35:29.889Z","v":0}

Could you fix it ?

![Screenshot_2](https://github.com/user-attachments/assets/6cacc03c-b03a-4c33-b561-ba45aa0abd6c)

**Comment by samsdogjack** [comment]
Hello, I think that binance chain is blocked if trying to connect through a United States IP address. If you could route your IP a different way you could possibly get connected.

**Comment by sekozzi** [comment]
Hello,

As I understand and as you say, the reason of this issue is binance that restrict about some country ip.

**Comment by Master199898** [comment]
Good evening guys, I also have the same problem, but I don't have authentication problems in the log.
Has anyone solved it?

**Comment by georgmails** [comment]
thanks

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Babyze** [comment]
If you tried it on Windows OS, I think you should sync the date and time on your Windows every day (or create a schedule for it) and re-run bot docker.

**Comment by chrisleekr** [comment]
Closing this as a refactored v1 has been released. It's no longer relevant to the latest code.
